# config.yaml
# Palavras-chave para identificar colunas importantes
column_candidates:
  date: [data, date, dt, competencia, competência, movimento, lançamento, lancamento]
  desc: [historico, histórico, descricao, descrição, description, documento, complemento, favorecido]
  value: [valor, amount, vl, val, "valor (r$)", r$, total]
  debit: [debito, débito, db, saída, saida]
  credit: [credito, crédito, cr, entrada]
  dc: [d/c, dc, tipo, natureza]
  protocol: [protocolo, numero, número, nr, ref, ref.]

# Padrões de texto para filtrar linhas inúteis (regex, case-insensitive)
patterns:
  lixo:
    - saldo\s*(anterior|final|do\s+dia)
    - total\s*geral
    - p[aá]g\.\s*\d+
    - via\s+do\s+cliente
    - comprovante
    - ag[eê]ncia
    - conta
    - extrato\s+(?:banc[aá]rio|simplificado)
    - n[oº]\s*doc(?:umento)?
    - autentica[cç][aã]o

# Configurações para o enriquecimento com IA
ai:
  prompt: >
    Você é um assistente especialista em contabilidade. Sua tarefa é analisar uma
    lista de transações financeiras em formato JSON. Para cada transação, você deve:
    1. Classificar a transação em uma das seguintes categorias: {categories}.
    2. Extrair o nome da "Contraparte" (a pessoa ou empresa com quem a transação foi feita). Se não houver, deixe nulo.
    3. Adicionar uma "Nota" curta se houver algo ambíguo ou que precise de atenção.
    
    Retorne APENAS um objeto JSON válido contendo uma única chave "transacoes",
    que é uma lista com os itens enriquecidos. Mantenha os campos originais. A resposta deve ter exatamente o mesmo número de itens da entrada.

  categories:
    - Entrada
    - Saída
    - Tarifa Bancária
    - Transferência
    - PIX Recebido
    - PIX Enviado
    - Pagamento de Boleto
    - Compra no Cartão
    - Salário
    - Pagamento de Impostos
    - Investimento
    - Resgate
    - Outros

  model: "gpt-4o-mini"
  batch_size: 50